resource_group_name               = "example-rg"
location                          = "East US"
vm_size                           = "Standard_B1s"
admin_username                    = "adminuser"
admin_password                    = "P@ssw0rd1234!"
virtual_network_name              = "existing-vnet"
virtual_network_resource_group_name = "existing-vnet-rg"
subnet_name                       = "existing-subnet"
