resource_group_name               = "ContosoAll"
location                          = "East US"
vm_size                           = "Standard_B1s"
admin_username                    = "adminuser"
admin_password                    = "P@ssw0rd1234!"
virtual_network_name              = "Vnet01"
virtual_network_resource_group_name = "ContosoAll"
subnet_name                       = "Default"
